// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.4
// source: pex.pex-proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 体温EMQX服务
type TemperatureEMQXReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureEMQXReq) Reset() {
	*x = TemperatureEMQXReq{}
	mi := &file_pex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureEMQXReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureEMQXReq) ProtoMessage() {}

func (x *TemperatureEMQXReq) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureEMQXReq.ProtoReflect.Descriptor instead.
func (*TemperatureEMQXReq) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{0}
}

type TemperatureEMQXResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemperatureEMQXResp) Reset() {
	*x = TemperatureEMQXResp{}
	mi := &file_pex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemperatureEMQXResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemperatureEMQXResp) ProtoMessage() {}

func (x *TemperatureEMQXResp) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemperatureEMQXResp.ProtoReflect.Descriptor instead.
func (*TemperatureEMQXResp) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{1}
}

// 血糖EMQX服务
type BloodGlucoseEMQXReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodGlucoseEMQXReq) Reset() {
	*x = BloodGlucoseEMQXReq{}
	mi := &file_pex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodGlucoseEMQXReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodGlucoseEMQXReq) ProtoMessage() {}

func (x *BloodGlucoseEMQXReq) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodGlucoseEMQXReq.ProtoReflect.Descriptor instead.
func (*BloodGlucoseEMQXReq) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{2}
}

type BloodGlucoseEMQXResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodGlucoseEMQXResp) Reset() {
	*x = BloodGlucoseEMQXResp{}
	mi := &file_pex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodGlucoseEMQXResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodGlucoseEMQXResp) ProtoMessage() {}

func (x *BloodGlucoseEMQXResp) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodGlucoseEMQXResp.ProtoReflect.Descriptor instead.
func (*BloodGlucoseEMQXResp) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{3}
}

// 血压EMQX服务
type BloodPressureEMQXReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodPressureEMQXReq) Reset() {
	*x = BloodPressureEMQXReq{}
	mi := &file_pex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodPressureEMQXReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodPressureEMQXReq) ProtoMessage() {}

func (x *BloodPressureEMQXReq) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodPressureEMQXReq.ProtoReflect.Descriptor instead.
func (*BloodPressureEMQXReq) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{4}
}

type BloodPressureEMQXResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodPressureEMQXResp) Reset() {
	*x = BloodPressureEMQXResp{}
	mi := &file_pex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodPressureEMQXResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodPressureEMQXResp) ProtoMessage() {}

func (x *BloodPressureEMQXResp) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodPressureEMQXResp.ProtoReflect.Descriptor instead.
func (*BloodPressureEMQXResp) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{5}
}

// 血氧EMQX服务
type BloodOxygenEMQXReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodOxygenEMQXReq) Reset() {
	*x = BloodOxygenEMQXReq{}
	mi := &file_pex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodOxygenEMQXReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodOxygenEMQXReq) ProtoMessage() {}

func (x *BloodOxygenEMQXReq) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodOxygenEMQXReq.ProtoReflect.Descriptor instead.
func (*BloodOxygenEMQXReq) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{6}
}

type BloodOxygenEMQXResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodOxygenEMQXResp) Reset() {
	*x = BloodOxygenEMQXResp{}
	mi := &file_pex_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodOxygenEMQXResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodOxygenEMQXResp) ProtoMessage() {}

func (x *BloodOxygenEMQXResp) ProtoReflect() protoreflect.Message {
	mi := &file_pex_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodOxygenEMQXResp.ProtoReflect.Descriptor instead.
func (*BloodOxygenEMQXResp) Descriptor() ([]byte, []int) {
	return file_pex_proto_rawDescGZIP(), []int{7}
}

var File_pex_proto protoreflect.FileDescriptor

const file_pex_proto_rawDesc = "" +
	"\n" +
	"\tpex.pex-proto\x12\x05proto\"\x14\n" +
	"\x12TemperatureEMQXReq\"\x15\n" +
	"\x13TemperatureEMQXResp\"\x15\n" +
	"\x13BloodGlucoseEMQXReq\"\x16\n" +
	"\x14BloodGlucoseEMQXResp\"\x16\n" +
	"\x14BloodPressureEMQXReq\"\x17\n" +
	"\x15BloodPressureEMQXResp\"\x14\n" +
	"\x12BloodOxygenEMQXReq\"\x15\n" +
	"\x13BloodOxygenEMQXResp2\xba\x02\n" +
	"\aEMQXSrv\x12H\n" +
	"\x0fTemperatureEMQX\x12\x19.pex-proto.TemperatureEMQXReq\x1a\x1a.pex-proto.TemperatureEMQXResp\x12K\n" +
	"\x10BloodGlucoseEMQX\x12\x1a.pex-proto.BloodGlucoseEMQXReq\x1a\x1b.pex-proto.BloodGlucoseEMQXResp\x12N\n" +
	"\x11BloodPressureEMQX\x12\x1b.pex-proto.BloodPressureEMQXReq\x1a\x1c.pex-proto.BloodPressureEMQXResp\x12H\n" +
	"\x0fBloodOxygenEMQX\x12\x19.pex-proto.BloodOxygenEMQXReq\x1a\x1a.pex-proto.BloodOxygenEMQXRespB\x03Z\x01/b\x06proto3"

var (
	file_pex_proto_rawDescOnce sync.Once
	file_pex_proto_rawDescData []byte
)

func file_pex_proto_rawDescGZIP() []byte {
	file_pex_proto_rawDescOnce.Do(func() {
		file_pex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pex_proto_rawDesc), len(file_pex_proto_rawDesc)))
	})
	return file_pex_proto_rawDescData
}

var file_pex_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pex_proto_goTypes = []any{
	(*TemperatureEMQXReq)(nil),    // 0: pex-proto.TemperatureEMQXReq
	(*TemperatureEMQXResp)(nil),   // 1: pex-proto.TemperatureEMQXResp
	(*BloodGlucoseEMQXReq)(nil),   // 2: pex-proto.BloodGlucoseEMQXReq
	(*BloodGlucoseEMQXResp)(nil),  // 3: pex-proto.BloodGlucoseEMQXResp
	(*BloodPressureEMQXReq)(nil),  // 4: pex-proto.BloodPressureEMQXReq
	(*BloodPressureEMQXResp)(nil), // 5: pex-proto.BloodPressureEMQXResp
	(*BloodOxygenEMQXReq)(nil),    // 6: pex-proto.BloodOxygenEMQXReq
	(*BloodOxygenEMQXResp)(nil),   // 7: pex-proto.BloodOxygenEMQXResp
}
var file_pex_proto_depIdxs = []int32{
	0, // 0: pex-proto.EMQXSrv.TemperatureEMQX:input_type -> pex-proto.TemperatureEMQXReq
	2, // 1: pex-proto.EMQXSrv.BloodGlucoseEMQX:input_type -> pex-proto.BloodGlucoseEMQXReq
	4, // 2: pex-proto.EMQXSrv.BloodPressureEMQX:input_type -> pex-proto.BloodPressureEMQXReq
	6, // 3: pex-proto.EMQXSrv.BloodOxygenEMQX:input_type -> pex-proto.BloodOxygenEMQXReq
	1, // 4: pex-proto.EMQXSrv.TemperatureEMQX:output_type -> pex-proto.TemperatureEMQXResp
	3, // 5: pex-proto.EMQXSrv.BloodGlucoseEMQX:output_type -> pex-proto.BloodGlucoseEMQXResp
	5, // 6: pex-proto.EMQXSrv.BloodPressureEMQX:output_type -> pex-proto.BloodPressureEMQXResp
	7, // 7: pex-proto.EMQXSrv.BloodOxygenEMQX:output_type -> pex-proto.BloodOxygenEMQXResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pex_proto_init() }
func file_pex_proto_init() {
	if File_pex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pex_proto_rawDesc), len(file_pex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pex_proto_goTypes,
		DependencyIndexes: file_pex_proto_depIdxs,
		MessageInfos:      file_pex_proto_msgTypes,
	}.Build()
	File_pex_proto = out.File
	file_pex_proto_goTypes = nil
	file_pex_proto_depIdxs = nil
}
